### PR TITLE
Add webserver port parameter (netstat/lsof not available on restricted unix platforms like Heroku) until PhantomJS webserver port issue is fixed.

### PR DESCRIPTION
**Pull request by leeopencare**
Lack of netstat/lsof limited our use case (though lsof would have still required a PR), I'd like to propose this work around until the phantom issue is fixed, I am going to dive into that.

### CODE REVIEW

**Comment by leeopencare** [comment]
Any thoughts here @baudehlo?

**Comment by baudehlo** [comment]
Yeah probably makes sense I guess. Seems potentially very flaky though... But I guess it becomes buyer beware. I'll merge it when you add docs for it.

**Comment by puzrin** [comment]
@leeopencare do you have `ss` on your platform (it's scheduled for upcoming changes)? Forcing port is not ideal solution for multiprocess environment.

**Comment by puzrin** [comment]
Now `iproute2` is supported and `net-tools` used for fallback on old distros. https://github.com/baudehlo/node-phantom-simple/commit/817aeb974417b2939c30df9f6388a65c88bb29a8

 I guess, that should help and this PR will not be needed. Please, test master. I tend to close this PR by timeout soon, if no updates come.

**Comment by puzrin** [comment]
Closing - timed out.

**Pull request closed without merging**
