### PR TITLE
Added a flag that stops longpolling for exited browsers

### PR DESCRIPTION
**Pull request by RavenHursT**

### CODE REVIEW

**Comment by baudehlo** [comment]
What's the reason for making this flag uppercase?

**Comment by puzrin** [comment]
@baudehlo i guess, similar to `.POSTING` https://github.com/CaptoraInc/node-phantom-simple/blob/203ceebf1123adef4db835b217e8d9247d11af8a/node-phantom-simple.js#L407

@Kirill89 will take a look what can we do with it.

**Comment by puzrin** [comment]
Solved by https://github.com/baudehlo/node-phantom-simple/commit/126cd63c848c96d020c49b83e0b527cd85226b22

**Comment by RavenHursT** [comment]
Awesome.  Glad this was fixed in the other PR.  Just for clarificaiton, I orginially considered using ```phantom.killed``` as the value to base the conditional off of, the only reason I went w/ creating a separate flag was because of another conditional in the code that I saw: https://github.com/baudehlo/node-phantom-simple/blob/126cd63c848c96d020c49b83e0b527cd85226b22/node-phantom-simple.js#L619

I was conscerned that, since the ```dead || phantom.killed``` was used elsewhere, that we would not be catching some use cases and would still see some CPU leakage.

It looks like ```dead``` is being set to ```true``` if and when phantom throws the 'exit' event.  Should we be checking against that value in the conditional used for killing the long-poll as well?

**Comment by RavenHursT** [comment]
@puzrin, any feedback on the above?  Just want to make sure we're not missing an edge case w/ the PR that was merged for this..

**Comment by puzrin** [comment]
@RavenHursT sorry, busy with embedza design & bugs. I did a mark for Kir to take a look in 1-2 days.

**Comment by RavenHursT** [comment]
Awesome.  Thanks @puzrin

**Comment by Kirill89** [comment]
@RavenHursT looks like you are right. I will fix it. Thanks for your help.

**Comment by RavenHursT** [comment]
Np @Kirill89 Can you ping back here whenever this has been updated and released so I can pull?

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/commits/master

**Comment by RavenHursT** [comment]
Awesome.  thanks guys.

**Pull request closed without merging**
