### PR TITLE
Added PhantomJS 2.0 clearMemoryCache() method

### PR DESCRIPTION
**Pull request by RavenHursT**
https://github.com/baudehlo/node-phantom-simple/issues/63

### CODE REVIEW

**Comment by puzrin** [comment]
Please, add test.

**Comment by RavenHursT** [comment]
Not exactly sure how I'd do that.. some direction please? (Haven't done many cross-fork PRs)

**Comment by puzrin** [comment]
Seems those fns are not covered with tests at all. Ok, one more untested fn will not change anything :)

**Comment by RavenHursT** [comment]
FWIW: https://github.com/CaptoraInc/node-phantom-simple/commit/c9ed23214070328adba76588b4e9ba76eb50e0d8

**Comment by puzrin** [comment]
Why did you touched second test (stripped some lines)?

**Comment by RavenHursT** [comment]
Oh.. I accidentally put my stuff in that test first.. must've taken the lines out when I copy-pasted my lines over to the new file.  Sorry..

**Pull request merged**
