### PR TITLE
Fix Phantom immediate exit check

### PR DESCRIPTION
**Pull request by siboulet**
Prior to 2.1.0 there was a check to handle case where phantomjs process
exited prematurely. This check was removed in 504f87e. This could happen
for example when a shared library is missing causing the phantomjs
process to fail spawning.

### CODE REVIEW

**Comment by siboulet** [comment]
Any chances this can be merged? Any feedback welcome.

**Comment by puzrin** [comment]
Sorry, missed it. Will ask @Kirill89 to see tommorow

**Comment by puzrin** [comment]
@joscha is this PR good for you? You were the last person who commited fixes about unexpexted phantom exit cases.

**Comment by joscha** [comment]
The semantics look good, however I am not sure what changed, so we don't have to wait those 100ms any longer - @siboulet any chance you can give more details on this fix?

**Comment by siboulet** [comment]
@joscha current implementation (waiting 100ms) no longer works since exitCode is never being updated and was removed here https://github.com/baudehlo/node-phantom-simple/commit/504f87e2e0a69ee351e423eb2a0a93757d225d53#diff-412ce2583b40d875a4b004b1a9b4265bL162

This patch does 2 things:

1) Fix properly detecting when phantomjs fails to spawn / immediate exit. Since 504f87e failing to spawn phantomjs is no longer properly being detected.
2) Improve immediate exit detection. Instead of using a timer, register an exit event on the phantomjs spawn process. Remove the exit event handler after the phantomjs "Ready" line is properly parsed.

**Comment by joscha** [comment]
I see - I missed the removal earlier - the patch looks good for me then :+1:

**Comment by joscha** [comment]
I suppose we can't easily add a test for this? Maybe with using a "fake" Phantom executable?

**Comment by puzrin** [comment]
Let's merge it.

Sorry for delay. Please, note, that i'm not active developper of this project now - i joined for a limited time frame to fix a big list of pending issues at once (because this driver was the best of available). Although i was given permissions to pull & publish, i don't keep details in my head, and it may take some time to remember what happens. By default i tend to conservative policy to not break anything.

I hope, driver is stable after all fixes, but if anyone think active development needed and wish to participate - request owner for permissions.

**Pull request merged**
