### PR TITLE
README fixes

### PR DESCRIPTION
**Pull request by MaarekElets**
Fixes minor README errors and adds windowing requirement to slimerjs known issues.

### CODE REVIEW

**Comment by puzrin** [comment]
Wrong place for second commit. There are examples for `evaluate` + only unfixable. Also wording is not clear. It will be more useful fo users to have exact instructions in "install" section.

**Comment by MaarekElets** [comment]
OK....I'll move it up there and clarify.

**Comment by puzrin** [comment]
For example, travis sample https://github.com/baudehlo/node-phantom-simple/blob/master/.travis.yml#L6-L8 + link to Slimer's page with instruction.

**Comment by puzrin** [comment]
Could you squash all to single commit ("SlimerJS info update")?

**Pull request merged**
