### PR TITLE
Added SlimerJS support

### PR DESCRIPTION
**Pull request by puzrin**
Minimal changes for SlimerJS transparent support.

Now you can use both `require('phantomjs').path` and `require('slimerjs').path` for binary location. Already tested in [navit](https://github.com/nodeca/navit).

### CODE REVIEW

**Comment by puzrin** [comment]
@baudehlo will you accept it? We don't like to create/maintain a separate fork.

**Comment by baudehlo** [comment]
Yes, sorry, I really need to pass off maintainence of this module - I no
longer work at the company where I created it. PRs sit unaccepted for too
long. Volunteers welcome.

**Comment by puzrin** [comment]
I could spend some resources for sort time to close panding tails - list of open PRs/issues is not too big.

Do you have any special requirements (what should and what should not be done). It's your project, and i may be unfamiliar with your vision.

**Comment by baudehlo** [comment]
There's a PR I left unmerged because it breaks backcompat - but it should get merged and a full version bump happen. Other than that, no requirements. I'll make you an admin.

**Comment by puzrin** [comment]
Thanks for the trust. If possible:

- please add @Kirill89 to collaborators
- enable this project in your travis account
- add me to publishers (https://www.npmjs.com/~vitaly)

Do you prefer 2.0.0 instead of 1.3.0? The first waive of upcoming changes/bugfixes will not break API, only extend it. I will care about that.

**Comment by baudehlo** [comment]
Done done and done.

1.3.0 is better because the API hasn't changed. 2.0 should be reserved for
breaking APIs.

**Comment by baudehlo** [comment]
Oh one last requirement - don't break the reason I wrote the module - so that it works under cluster(). Though I believe they may have fixed the issue as of node 0.12 or in io.js. Not sure.

The problem is under cluster if you ask for port zero (I.e give me a random free port) they give you the same server in each child process. Hence the weird hoops this module jumps through to avoid that.

**Comment by puzrin** [comment]
Could you clarify problem? We don't ask for zero port. We analyze reply from bridge, that is always executed in separate process. Now use this logic:

- phantomjs always returns 0 port And !=0 pid
  - -> do cheats with network tools, by pid
- slimerjs returns !=0 port And 0 pid
 - happy immediately

If you run module under cluster, it will fork engine with bridge.js anyway, and nothing should be broken. As a bonus - when phantomjs fixed, and bridge starts to reply with correct port, detection will go in the same way as for slimerjs.

Do i miss something?

**Comment by baudehlo** [comment]
Yeah I started out using various other modules that create a server on port 0 and then pass the given port to the spawned process to talk to. But if you used cluster() in the controlling process (which we did) you ended up with all the phantom processes trying to talk to all the backends at the same time. This clearly doesn't work.

I submitted a bug in Node about this but they disagreed that it should work differently to all other port requests.

Phantom does the right thing when you ask for the http server on port zero, but doesn't (didn't?) report the actual port when asked for it - it always said the server was on port zero - and fixing the bug in phantom seemed fruitless as development was so slow (and they used an external lib for the http server anyway). Hence the stuff with lsof/netstat etc.

Does that help?

No other phantom module addresses this issue btw. Every single other module to talk to phantom was broken under cluster().

**Comment by puzrin** [comment]
As far as i remember, you fighten with different problem - PhantomJS does not report port, if assigned dynamically (`as listen(localhost:0)`). SlimerJS has no such problem, and returns correct value.

Race condition can happen if one try to force port number definition. We still use random port for slimer.

**Comment by puzrin** [comment]
If you mean, i should not "simplify" code with port detection - sure, no such plans :) . I understand, this is workaround for phantomjs bug, to operate right with multiple processes.

**Comment by baudehlo** [comment]
Sure, as long as the slimerjs project understands that that just plain doesn't work/scale (i.e. You will get a conflict at some point) that's fine. :)

**Pull request merged**
