### PR TITLE
setFn(): Add option to wrap with `phantom.callback` (Fixes #88)

### LINKED ISSUE #88: Missing a way to create phantom callbacks
As per [PhantomJS docs](http://phantomjs.org/api/webpage/property/paper-size.html), defining a header or footer when generating a PDF requires to provide a function wrapped by `phantom.callback()` (undocumented). We can already use `page#setFn()` to assign a function, but we're still missing a way to wrap it (or maybe I missed it).

One approach would be to augment `setFn()` to allow flagging a function that should be wrapped, another would be to create a new method altogether. Any thoughts?

Cheers

### PR DESCRIPTION
**Pull request by svvac**
See #88

### CODE REVIEW

**Comment by svvac** [comment]
Example for creating a footer:

```js
var browser, page; // Will hold references to browser and page for example concision

phantom.create({}, whenBrowserReady);

function whenBrowserReady (err, b) {
    if (err) throw err;

    browser = b;

  browser.createPage(whenPageCreated);
}

function whenPageCreated (err, p) {
    page = p;

    // Since actions are ran in order by the bridge, we can issue multiple async calls without
    // worrying about creating a new callback every time. This makes this snippet more readable
    // but I would advise creating a callback each time (maybe by promisifying the API to avoid
    // the "callback pyramid of doom" ;-)
    page.set('paperSize', { format: 'A4', direction: 'portrait', margin: '1cm' });
    page.set('paperSize.footer.height', '2cm');

    // That is what we're interested in:
    // Pass true before an eventual callback to tell the bridge to wrap the function with
    // `phantom#callback()`
    page.setFn('paperSize.footer.contents', function (pageNum, numPages) {
        return '<div style="text-align: center">' + pageNum + '/' + numPages + '</div>';
    }, true);

    page.open('http://github.com/', whenPageLoadedAndReady);
}

function whenPageLoadedAndReady (err, status) {
    if (err) throw err;
    if (status !== 'loaded') throw 'Could not load page';

    page.render('github-home.pdf', { format: 'PDF' });
}
```

**Comment by svvac** [comment]
See #88 for a discussion on how this approach compares with the one in PR #86

**Comment by puzrin** [comment]
Personally, i don't like api changes for single use case. That looks like over-engineering. Hardcoding (by property name) is much more simple for this case.

More samples from real world required for deeper API changes (i usually request >= 3 cases in my projects)

**Comment by svvac** [comment]
@puzrin With `phantom.callback()` being undocumented yet (confirmed upstream), I can't point you to other usecases. But IMHO, setting headers and footers (yet unsupported) seems like an important enough case to me since quite a lot of Phantom references on the net refer to PDF generation.

I'd argue that:
  * The API remains unchanged. You can continue to use `page#setFn()`as usual since the `wrap` argument is optional ;
  * Phantom devs saw the value of providing the function to userland and NOT automatically wrap functions set on these properties ;
  * Slimerjs doesnt seem to implement `page.paperSize` yet (as per the docs). There's no guarantee that when it does it will use a similar (let alone the same) mechanism when it does ;
  * I'll repeat the arguments from [this comment](/baudehlo/node-phantom-simple/issues/88#issuecomment-148488741): it tightly couples the code to phantom's approach and current API (if next version renames`paperSize`, the simple hardcoding will need to grow to incorporate version checks to remain backend-agnostic ;
  * In terms of over-engineering, PR #86 implements some kind of hardcoding by making substantially more changes to the code.

**Comment by puzrin** [comment]
Too many assumptions, IMHO. Basing design on such assumptions will cause messy api. That's my personal opinion, based on my experience. Also flag to wrap fn looks artificial - `phantom.callback` is not generic enougth to have separate param in signature.

Right now i'd suggest to use hardcoded wrappers, and update API if we ever get more info. Or keep it intact if nothing changes. I guess, nobody will even need to change this code in nearest future.

**Comment by puzrin** [comment]
Another alternative is to provide example, how to use advanced options of `pageSize`:

```js
setFn('setPageSize`, function(objToWrap) {
  // implementation
});
```

If anyone needs header/footer, he could use that example without any package change.

**Comment by puzrin** [comment]
Advanced page props implemented in https://github.com/baudehlo/node-phantom-simple/commit/af88f55014ffc553282df26b146d4fa077edfb9f, that's enougth for the now.

**Pull request closed without merging**
